exclude: '.*\.(pcap|pcapng|dat|txt)'
fail_fast: false
repos:
  - repo: local
    hooks:
      - id: check-clang-format-version
        name: Check clang-format version
        entry: python3 ./ci/check-clang-format-version.py
        language: system
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: check-symlinks
      - id: end-of-file-fixer
      - id: forbid-submodules
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
      - id: ruff # Run the linter.
        types_or: [ python ]
      - id: ruff-format  # Run the formatter.
        types_or: [ python ]
        args: [ --check ]
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: ["--style=file", "-i"]  # Use the .clang-format file for configuration and apply all fixes
        files: ^(Common\+\+|Packet\+\+|Pcap\+\+|Tests|Examples)/.*\.(cpp|h)$
      - id: cppcheck
        args: ["--std=c++11", "--language=c++", "--suppressions-list=cppcheckSuppressions.txt", "--inline-suppr", "--force"]
  - repo: https://github.com/BlankSpruce/gersemi
    rev: 0.15.1
    hooks:
    - id: gersemi
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        pass_filenames: false
  - repo: https://github.com/crate-ci/typos
    rev: v1.25.0
    hooks:
      - id: typos
        args: ['--config=typos-config.toml']
        pass_filenames: false
  - repo: https://github.com/lovesegfault/beautysh
    rev: v6.2.1
    hooks:
      - id: beautysh
