exclude: '.*\.(pcap|pcapng|dat|txt)'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0  # Use the ref you want to point at
    hooks:
    -   id: trailing-whitespace
    -   id: check-case-conflict
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
        args: ['--fix=lf']
