exclude: '.*\.(pcap|pcapng|dat|txt)'
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: end-of-file-fixer
    #   - id: mixed-line-ending
    #     args: ['--fix=lf']
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
#   - repo: https://github.com/pocc/pre-commit-hooks
#     rev: v1.3.5
#     hooks:
#       - id: clang-format
  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
  - repo: https://github.com/crate-ci/typos
    rev: v1.11.0
    hooks:
      - id: typos
        args: ['--config=typos-config.toml']
