sudo: required
language: cpp
services:
  - docker

matrix:
  include:
    - os: linux
      env:
        - DOCKER_IMAGE=ubuntu1404
    - os: linux
      env:
        - DOCKER_IMAGE=ubuntu1604
    - os: linux
      env:
        - DOCKER_IMAGE=centos7
    - os: linux
      env:
        - DOCKER_IMAGE=fedora26
    - os: linux
      env:
        - DOCKER_IMAGE=ubuntu1604-dpdk1611
        - DPDK_DIR=dpdk-stable-16.11.1
    - os: linux
      env:
        - DOCKER_IMAGE=ubuntu1604-dpdk1702
        - DPDK_DIR=dpdk-17.02
    - os: linux
      env:
        - DOCKER_IMAGE=ubuntu1604-pfring
        - PF_RING=True
    - os: osx
      compiler: clang
      osx_image: xcode6.4
    - os: osx
      compiler: clang
      osx_image: xcode7.3
    - os: osx
      compiler: clang
      osx_image: xcode8
    - os: osx
      compiler: clang
      osx_image: xcode8.1
    - os: osx
      compiler: clang
      osx_image: xcode8.2
    - os: osx
      compiler: clang
      osx_image: xcode8.3
    - os: osx
      compiler: clang
      osx_image: xcode9
    - os: osx
      compiler: clang
      osx_image: xcode9.1

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
       docker pull seladb/$DOCKER_IMAGE:latest;
       docker run -itd --name $DOCKER_IMAGE -v $(pwd):/PcapPlusPlus seladb/$DOCKER_IMAGE;
    fi

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./configure-mac_os_x.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker exec -i $DOCKER_IMAGE bash -c "cd PcapPlusPlus && ./configure-linux.sh --default"; fi
  - if [[ ! -z $DPDK_DIR ]]; then docker exec -i $DOCKER_IMAGE bash -c "cd PcapPlusPlus && ./configure-linux.sh --dpdk --dpdk-home /$DPDK_DIR"; fi
  - if [[ ! -z $PF_RING ]]; then docker exec -i $DOCKER_IMAGE bash -c "cd PcapPlusPlus && ./configure-linux.sh --pf-ring --pf-ring-home /PF_RING"; fi
  
script:
  - ERR_CODE=0
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
       make all || ERR_CODE=$?;
       cd Tests/Packet++Test && Bin/Packet++Test || ERR_CODE=$?;
       cd ../Pcap++Test && sudo Bin/Pcap++Test -n || ERR_CODE=$?;
       cd ../../ && sudo make install || ERR_CODE=$?;
    else
       docker exec -i $DOCKER_IMAGE bash -c "cd PcapPlusPlus && make all" || ERR_CODE=$?;
       docker exec -i $DOCKER_IMAGE bash -c "cd PcapPlusPlus/Tests/Packet++Test && Bin/Packet++Test" || ERR_CODE=$?;
       docker exec -i $DOCKER_IMAGE bash -c "cd PcapPlusPlus/Tests/Pcap++Test && Bin/Pcap++Test -n -k 0" || ERR_CODE=$?;
       docker exec -i $DOCKER_IMAGE bash -c "cd PcapPlusPlus && make install" || ERR_CODE=$?;
    fi
  - (exit $ERR_CODE)

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
       cd Examples/Tutorials/Tutorial-HelloWorld/;
       make -f Makefile.non_windows all;
       ./Tutorial-HelloWorld;
    else
       docker exec -i $DOCKER_IMAGE bash -c "cd PcapPlusPlus/Examples/Tutorials/Tutorial-HelloWorld/ && make -f Makefile.non_windows all && ./Tutorial-HelloWorld";
    fi
