[files]
extend-exclude = [  "*.toml",
                    "*.dat",
                    "codespell-ignore-list.txt",
                    "ci/",
                    "Dist/",
                    "mk/",
                    "3rdParty",
                    "Tests/ExamplesTest/expected_output/",
                    "Tests/ExamplesTest/pcap_examples/",
                    "Tests/Packet++Test/PacketExamples/",
                    "Tests/Pcap++Test/PcapExamples/",
                 ]

[default.extend-identifiers]
SSLSymetricEncryptionAlgorithm = "SSLSymetricEncryptionAlgorithm"
OsiModelSesionLayer = "OsiModelSesionLayer"
Sip181CallisBeingForwarded = "Sip181CallisBeingForwarded"

[default.extend-words]
ue = "ue"
loca = "loca"
inout = "inout"
ede = "ede"
tha = "tha"
gost = "gost"
ba = "ba"
lengt = "lengt"
referer = "referer"
allo = "allo"
pinter = "pinter"
helo = "helo"

[type.make]
extend-glob = []
check-file = false
