[files]
extend-exclude = [  "*.toml",
                    "*.dat",
                    "codespell-ignore-list.txt",
                    "ci/",
                    "Dist/",
                    "mk/",
                    "3rdParty",
                    "Tests/ExamplesTest/expected_output/",
                    "Tests/ExamplesTest/pcap_examples/",
                    "Tests/Packet++Test/PacketExamples/",
                    "Tests/Pcap++Test/PcapExamples/",
                 ]

[default.extend-identifiers]
SSLSymetricEncryptionAlgorithm = "SSLSymetricEncryptionAlgorithm"
OsiModelSesionLayer = "OsiModelSesionLayer"
Sip181CallisBeingForwarded = "Sip181CallisBeingForwarded"
# These identifiers below are coming from deprecated functions which is mentioned in cmake/package/READMEs/release_notes.txt
# They can be removed in next release (first release after v23.09) when the release notes are changed.
getMesageType = "getMesageType"
setMesageType = "setMesageType"
getExtensionsLenth = "getExtensionsLenth"
createHandhakeMessage = "createHandhakeMessage"

[default.extend-words]
ue = "ue"
loca = "loca"
inout = "inout"
ede = "ede"
tha = "tha"
gost = "gost"
ba = "ba"
lengt = "lengt"
referer = "referer"
allo = "allo"
pinter = "pinter"
helo = "helo"
hom = "hom"
pn = "pn"

[type.make]
extend-glob = []
check-file = false
