name: Fuzz CI
on:
  pull_request:
    branches: ["dev"]
  schedule:
    - cron: '0 0 * * 0' # Run every Sunday at midnight

permissions:
  contents: read

#jobs:
#  Fuzzing:
#    runs-on: ubuntu-latest
#    strategy:
#      fail-fast: true
#      matrix:
#        sanitizer: [address, undefined, memory]
#    steps:
#    - name: Build Fuzzers
#      id: build
#      uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@c2c0632831767ff05c568e7b552cef2801d739ff # master
#      with:
#        oss-fuzz-project-name: 'pcapplusplus'
#        dry-run: false
#        sanitizer: ${{ matrix.sanitizer }}
#    - name: Run Fuzzers
#      uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@c2c0632831767ff05c568e7b552cef2801d739ff # master
#      with:
#        oss-fuzz-project-name: 'pcapplusplus'
#        fuzz-seconds: 600
#        dry-run: false
#        sanitizer: ${{ matrix.sanitizer }}
#    - name: Upload Crash
#      uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
#      if: failure() && steps.build.outcome == 'success'
#      with:
#        name: artifacts
#        path: ./out/artifacts
